name: fitness_live
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+11
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.3
  image_picker: ^0.6.3+4
  line_icons: ^0.2.0
  path: ^1.6.4
  provider: ^4.0.4
  toggle_switch: ^0.1.8

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
